spring:
  application:
    name: ecommerce-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db

server:
  port: 8080

razorpay:
  key: rzp_test_S5iUglag8OB6LF
  secret: MFjOji9gguGM3vsDoZopmPYi




